USE [master]
GO

/****** Object:  Database [DBTest]    Script Date: 04.04.2019 23:25:46 ******/
CREATE DATABASE [DBTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBTest', FILENAME = N'E:\Programms\SQL Server 2017\MSSQL14.SQLSERVERMIRONOV\MSSQL\DATA\DBTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBTest_log', FILENAME = N'E:\Programms\SQL Server 2017\MSSQL14.SQLSERVERMIRONOV\MSSQL\DATA\DBTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DBTest] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBTest] SET  MULTI_USER 
GO

ALTER DATABASE [DBTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBTest] SET  READ_WRITE 
GO

